name: PowerShell script
author: Pooya Kharamesh
permissions:
  contents: write
  pull-requests: write
inputs:
  actor:
    description: The GitHub actor running the action
    required: false
    default: ${{ github.actor }}
  token:
    description: The GitHub token running the action
    required: false
    default: ${{ github.token }}
  parentTelemetryScopeJson:
    description: Specifies the parent telemetry scope for the telemetry signal
    required: false
    default: '{}'
  workflowToken:
    description: A GitHub token with permissions to modify workflows
    required: false
    default: ''
  tag_name:
    description: Tag name
    required: true
outputs:
  ReleaseNotes:
    description: Release note generated based on the changes
    value: ${{ steps.createreleasenotes.outputs.releaseNotes }}
runs:
  using: composite
  steps:
    - run: ${{ github.action_path }}/CreateReleaseNotes.ps1 -actor '${{ inputs.actor }}' -token '${{ inputs.token }}' -parentTelemetryScopeJson '${{ inputs.parentTelemetryScopeJson }}' -workflowToken '${{ inputs.workflowToken }}' -tag_name '${{ inputs.tag_name }}'
      id: createreleasenotes
      shell: PowerShell
branding:
  icon: terminal
  color: blue