name: PowerShell script
author: Freddy Kristiansen
inputs:
  actor:
    description: The GitHub actor running the action
    required: false
    default: ${{ github.actor }}
  token:
    description: The GitHub token running the action
    required: false
    default: ${{ github.token }}
  parentTelemetryScopeJson:
    description: Specifies the parent telemetry scope for the telemetry signal
    required: false
    default: '{}'
  projects:
    description: Projects to deploy (default is all)
    required: false
    default: '*'
  environmentName:
    description: Name of environment to deploy to
    required: true
  artifacts:
    description: Artifacts to deploy
    required: true
  type:
    description: Type of deployment (CD or Publish)
    required: false
    default: 'CD'
runs:
  using: composite
  steps:
    - run: ${{ github.action_path }}/Deploy.ps1 -actor '${{ inputs.actor }}' -token '${{ inputs.token }}' -parentTelemetryScopeJson '${{ inputs.parentTelemetryScopeJson }}' -projects '${{ inputs.projects }}' -environmentName '${{ inputs.environmentName }}' -artifacts '${{ inputs.artifacts }}' -type '${{ inputs.type }}'
      shell: PowerShell
branding:
  icon: terminal
  color: blue
